// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearClientLogs() {
  return window['go']['main']['App']['ClearClientLogs']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetClientLogs(arg1) {
  return window['go']['main']['App']['GetClientLogs'](arg1);
}

export function GetClientStatus() {
  return window['go']['main']['App']['GetClientStatus']();
}

export function GetSessionStatus(arg1) {
  return window['go']['main']['App']['GetSessionStatus'](arg1);
}

export function IsClientRunning() {
  return window['go']['main']['App']['IsClientRunning']();
}

export function LoadConfig(arg1) {
  return window['go']['main']['App']['LoadConfig'](arg1);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function StartClient(arg1) {
  return window['go']['main']['App']['StartClient'](arg1);
}

export function StopClient(arg1) {
  return window['go']['main']['App']['StopClient'](arg1);
}

export function SystemProxyDisable(arg1) {
  return window['go']['main']['App']['SystemProxyDisable'](arg1);
}

export function SystemProxyEnable(arg1) {
  return window['go']['main']['App']['SystemProxyEnable'](arg1);
}

export function SystemProxyStatus(arg1) {
  return window['go']['main']['App']['SystemProxyStatus'](arg1);
}
