// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearClientLogs():Promise<void>;

export function GetClientLogs(arg1:number):Promise<Array<string>>;

export function GetClientStatus():Promise<main.ClientStatus>;

export function IsClientRunning():Promise<boolean>;

export function LoadConfig(arg1:string):Promise<Record<string, any>>;

export function SaveConfig(arg1:string,arg2:Record<string, any>):Promise<void>;

export function StartClient(arg1:string):Promise<void>;

export function StopClient(arg1:boolean):Promise<void>;

export function SystemProxyDisable(arg1:string):Promise<void>;

export function SystemProxyEnable(arg1:string):Promise<void>;

export function SystemProxyStatus(arg1:string):Promise<string>;
